### ISSUE TITLE
Update Helm Chart

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/elasticsearch-kubernetes#9]
Make sure ES Helm chart is up to date with ES repo (or vis-versa). 
Check API versions, check all docker images are not pulling ‘latest’, if versioned, check the image version is recent. 
Link the repo in the README and link the Helm chart in the repo README. 
Make sure everything is running in Kube-logging namespace
Up Helm chart version.

Note:  Inquire if team has established Helm style guideline before starting.

**Comment by davidewatson** [comment]
Superceeded by https://github.com/samsung-cnct/issues/issues/59
